on:
    push:
        branches:
            - main
            - master
    pull_request:
    schedule:
        - cron: 30 3 * 1 *

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version:
                    ["3.7", "3.8", "3.9", "3.10", "pypy3.7", "pypy3.8"]
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Display Python version
              run: python --version
            - name: Run pytest
              run: python -m pytest
